export const PLANS = {
  free: {
    name: "Free",
    description: "Try it out",
    price: 0,
    videos: 1,
    maxStorage: 2,
    renders: 10,
    quality: "1080p_max",
    watermark: true,
    popular: false,
    cta: "Get Started Free",
    features: [
      "1 video/month",
      "10 clip renders/month",
      "1080p max export",
      "HookCut.com watermark",
      "All 6 caption styles",
      "Smart Reel (AI)",
      "AI face tracking",
      "Hook A/B variants",
      "AI titles & hashtags",
      "Email support",
    ],
  },
  starter: {
    name: "Starter",
    description: "For individual creators",
    price: 9,
    videos: 5,
    maxStorage: 10,
    renders: 40,
    quality: "native",
    watermark: false,
    popular: false,
    cta: "Get Started",
    features: [
      "5 videos/month",
      "40 clip renders/month",
      "Full quality export",
      "No watermark",
      "All 6 caption styles",
      "Smart Reel (AI)",
      "AI face tracking",
      "Hook A/B variants",
      "AI titles & hashtags",
      "Email support",
    ],
  },
  pro: {
    name: "Pro",
    description: "For serious creators",
    price: 19,
    videos: 25,
    maxStorage: 50,
    renders: 100,
    quality: "native",
    watermark: false,
    popular: true,
    cta: "Get Started",
    features: [
      "25 videos/month",
      "100 clip renders/month",
      "Full quality export",
      "No watermark",
      "Everything in Starter",
      "Priority support",
      "Animated captions (coming soon)",
      "API access (coming soon)",
    ],
  },
  agency: {
    name: "Agency",
    description: "For teams & agencies",
    price: 39,
    videos: -1,
    maxStorage: -1,
    renders: 250,
    quality: "native",
    watermark: false,
    popular: false,
    cta: "Get Started",
    features: [
      "Unlimited videos/month",
      "250 clip renders/month",
      "Full quality export (up to 4K)",
      "No watermark",
      "Everything in Pro",
      "Custom branding (coming soon)",
      "Team seats (coming soon)",
      "Dedicated support",
    ],
  },
} as const;

export const ADDON_PACK = {
  price: 9,
  renders: 30,
  maxPerMonth: 200,
} as const;

export type PlanKey = keyof typeof PLANS;

export const STRIPE_PRICES: Record<string, string> = {
  starter: "price_1T4oE83CjW6GJ5ED9WzYBlKp",
  pro: "price_1T4oEa3CjW6GJ5EDRjoWkUi4",
  agency: "price_1T4oF13CjW6GJ5EDGtzLDtzP",
  render_pack: "price_1T4oFM3CjW6GJ5EDxLMIsrwD",
};
